### PR TITLE
Fixed bug in TimeSeries when multiple targets have different time spans

### PR DESCRIPTION
**Pull request by Jell**
When drawing a TimeSerieView with multiple targets that have different time spans, the range on the X-axis did not respect the total range of all the series, but only considered the first serie.

This commit should fix that.

Hope this helps!

### CODE REVIEW

**Comment by jondot** [comment]
Awesome, thanks!

**Comment by cerw** [comment]
How do i define multipla targets in JSON API url ? ta

**Comment by jondot** [comment]
@cerw see here, https://github.com/jondot/graphene/issues/61

**Comment by cerw** [comment]
All working thanks :)

**Pull request merged**
