### PR TITLE
support of a define yMax

### PR DESCRIPTION
**Pull request by davidchau**
Support Graphite's yMax. Now it gets the yMax from the request or from
the option for the timeSeries or the max of the serie

related to issues 12

### CODE REVIEW

**Comment by jondot** [comment]
Thanks again, love the concept of lifting value from the URL. Will merge when infront of a terminal later today

**Comment by davidchau** [comment]
Great! Can you add me in the list of contributors in the documentation?

**Comment by jondot** [comment]
Yes of course, once in a while I do a scan of all of the commits, and re-align the contributor list. I'll be more than happy to do it right now :+1:

**Comment by davidchau** [comment]
Did you have the chance to merge the changes?

**Comment by jondot** [comment]
Sorry, working on it right now, thanks for bumping

**Pull request merged**
